2025-03-29 17:34:00.689 [info] Extension host with pid 76205 started
2025-03-29 17:34:00.809 [info] ExtensionService#_doActivateExtension google.geminicodeassist, startup: false, activationEvent: 'onView:cloudcode.gemini.chatView'
2025-03-29 17:34:00.813 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2025-03-29 17:34:00.814 [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python'
2025-03-29 17:34:03.767 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2025-03-29 17:34:03.796 [info] ExtensionService#_doActivateExtension google.cloud-shell, startup: false, activationEvent: 'onTerminalProfile:cloudshell.default'
2025-03-29 17:34:03.823 [info] Lock '/home/sandyaa2004/.codeoss/data/User/workspaceStorage/62bec47d/vscode.lock': Lock acquired.
2025-03-29 17:34:04.012 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2025-03-29 17:34:04.013 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2025-03-29 17:34:04.265 [error] Error: spawn /google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/python-env-tools/bin/pet ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:286:19)
	at onErrorNT (node:internal/child_process:484:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2025-03-29 17:34:04.619 [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
2025-03-29 17:34:04.620 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2025-03-29 17:34:04.621 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2025-03-29 17:34:04.885 [info] Eager extensions activated
2025-03-29 17:34:04.885 [info] ExtensionService#_doActivateExtension EditorConfig.EditorConfig, startup: false, activationEvent: 'onStartupFinished'
2025-03-29 17:34:04.886 [info] ExtensionService#_doActivateExtension googlecloudtools.cloudcode, startup: false, activationEvent: 'onStartupFinished'
2025-03-29 17:34:04.886 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2025-03-29 17:34:04.887 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2025-03-29 17:56:24.455 [error] [ms-python.python] provider FAILED
2025-03-29 17:56:24.475 [error] Error: FileNotFoundError: [Errno 2] No such file or directory: '/home/sandyaa2004/Untitled-1'
    at ae (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2049071)
    at oe (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2047031)
    at Immediate.<anonymous> (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2043325)
    at processImmediate (node:internal/timers:483:21)
2025-03-29 17:56:25.123 [error] [ms-python.python] provider FAILED
2025-03-29 17:56:25.124 [error] Error: FileNotFoundError: [Errno 2] No such file or directory: '/home/sandyaa2004/Untitled-1'
    at ae (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2049071)
    at oe (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2047031)
    at Immediate.<anonymous> (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2043325)
    at processImmediate (node:internal/timers:483:21)
2025-03-29 17:56:27.925 [error] [ms-python.python] provider FAILED
2025-03-29 17:56:27.926 [error] Error: FileNotFoundError: [Errno 2] No such file or directory: '/home/sandyaa2004/Untitled-1'
    at ae (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2049071)
    at oe (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2047031)
    at Immediate.<anonymous> (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2043325)
    at processImmediate (node:internal/timers:483:21)
2025-03-29 17:56:51.122 [warning] Illegal argument: TextEditor(vs.editor.ICodeEditor:3,$model9)
2025-03-29 17:59:10.694 [error] [ms-python.python] provider FAILED
2025-03-29 17:59:10.695 [error] Error: FileNotFoundError: [Errno 2] No such file or directory: '/home/sandyaa2004/Untitled-1'
    at ae (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2049071)
    at oe (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2047031)
    at Immediate.<anonymous> (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2043325)
    at processImmediate (node:internal/timers:483:21)
2025-03-29 17:59:20.404 [error] [ms-python.python] provider FAILED
2025-03-29 17:59:20.405 [error] Error: FileNotFoundError: [Errno 2] No such file or directory: '/home/sandyaa2004/Untitled-1'
    at ae (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2049071)
    at oe (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2047031)
    at Immediate.<anonymous> (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2043325)
    at processImmediate (node:internal/timers:483:21)
2025-03-29 17:59:33.836 [error] [ms-python.python] provider FAILED
2025-03-29 17:59:33.836 [error] Error: FileNotFoundError: [Errno 2] No such file or directory: '/home/sandyaa2004/Untitled-1'
    at ae (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2049071)
    at oe (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2047031)
    at Immediate.<anonymous> (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2043325)
    at processImmediate (node:internal/timers:483:21)
2025-03-29 17:59:42.748 [warning] Illegal argument: TextEditor(vs.editor.ICodeEditor:3,$model11)
2025-03-29 18:07:06.000 [error] [ms-python.python] provider FAILED
2025-03-29 18:07:06.000 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
    at ae (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2049071)
    at oe (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2047031)
    at Immediate.<anonymous> (/google/devshell/editor/code-oss-for-cloud-shell/extensions/ms-python.python/out/client/extension.js:2:2043325)
    at processImmediate (node:internal/timers:483:21)
